"""empty message

Revision ID: 5568469b4adb
Revises: d0934e8f318a
Create Date: 2024-09-10 02:46:15.054194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5568469b4adb'
down_revision = 'd0934e8f318a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_people'], ['people.id_people'], ),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id_planet'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('id_starship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_starship', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('favorite')
    # ### end Alembic commands ###
