"""empty message

Revision ID: c7e7c4dc53bc
Revises: f6abf93078a9
Create Date: 2024-09-10 00:52:07.518996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e7c4dc53bc'
down_revision = 'f6abf93078a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('Gender',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_column('Mass')
        batch_op.drop_column('Skin_color')
        batch_op.drop_column('Homeworld')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Homeworld', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Skin_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Mass', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.alter_column('Gender',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
