"""empty message

Revision ID: d0934e8f318a
Revises: 56c24346a5c3
Create Date: 2024-09-10 02:44:12.967483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0934e8f318a'
down_revision = '56c24346a5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starships')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_id_starship_fkey', type_='foreignkey')
        batch_op.drop_column('id_starship')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_id_starship_fkey', type_='foreignkey')
        batch_op.drop_column('id_starship')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_starship', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('people_id_starship_fkey', 'starships', ['id_starship'], ['id_starship'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_starship', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorite_id_starship_fkey', 'starships', ['id_starship'], ['id_starship'])

    op.create_table('starships',
    sa.Column('id_starship', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Model', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('Starship_class', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('Length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Crew', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Passengers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_starship', name='starships_pkey'),
    sa.UniqueConstraint('Model', name='starships_Model_key'),
    sa.UniqueConstraint('Name', name='starships_Name_key')
    )
    # ### end Alembic commands ###
