"""empty message

Revision ID: e6bca0728de6
Revises: c7e7c4dc53bc
Create Date: 2024-09-10 00:56:32.023331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6bca0728de6'
down_revision = 'c7e7c4dc53bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('Birth_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('Eye_color',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('Hair_color',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('Hair_color',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('Eye_color',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('Birth_year',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
