"""empty message

Revision ID: f6abf93078a9
Revises: fa6986cee813
Create Date: 2024-09-05 22:02:33.000902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6abf93078a9'
down_revision = 'fa6986cee813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Diameter', sa.Integer(), nullable=True),
    sa.Column('Rotation_period', sa.Integer(), nullable=True),
    sa.Column('Orbital_period', sa.Integer(), nullable=True),
    sa.Column('Population', sa.Integer(), nullable=True),
    sa.Column('Climate', sa.String(length=50), nullable=True),
    sa.Column('Terrain', sa.String(length=50), nullable=True),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_planet'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('starships',
    sa.Column('id_starship', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Model', sa.String(length=50), nullable=False),
    sa.Column('Starship_class', sa.String(length=100), nullable=True),
    sa.Column('Manufacturer', sa.String(length=100), nullable=True),
    sa.Column('Cost_in_credits', sa.Integer(), nullable=True),
    sa.Column('Length', sa.Float(), nullable=True),
    sa.Column('Crew', sa.Integer(), nullable=True),
    sa.Column('Passengers', sa.Integer(), nullable=True),
    sa.Column('Max_atmosphering_speed', sa.Integer(), nullable=True),
    sa.Column('Hyperdrive_rating', sa.Float(), nullable=True),
    sa.Column('Cargo_capacity', sa.String(length=250), nullable=False),
    sa.Column('Consumables', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id_starship'),
    sa.UniqueConstraint('Model'),
    sa.UniqueConstraint('Name')
    )
    op.create_table('people',
    sa.Column('id_people', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Gender', sa.Integer(), nullable=True),
    sa.Column('Birth_year', sa.Integer(), nullable=True),
    sa.Column('Eye_color', sa.Integer(), nullable=True),
    sa.Column('Hair_color', sa.Integer(), nullable=True),
    sa.Column('Mass', sa.String(length=50), nullable=True),
    sa.Column('Skin_color', sa.String(length=50), nullable=True),
    sa.Column('Homeworld', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.Column('id_starship', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id_planet'], ),
    sa.ForeignKeyConstraint(['id_starship'], ['starships.id_starship'], ),
    sa.PrimaryKeyConstraint('id_people')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_people', sa.Integer(), nullable=True),
    sa.Column('id_planet', sa.Integer(), nullable=True),
    sa.Column('id_starship', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_people'], ['people.id_people'], ),
    sa.ForeignKeyConstraint(['id_planet'], ['planet.id_planet'], ),
    sa.ForeignKeyConstraint(['id_starship'], ['starships.id_starship'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('people')
    op.drop_table('starships')
    op.drop_table('planet')
    # ### end Alembic commands ###
